<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\eventlogs' => 'modules\\system\\controllers\\eventlogs.php',
  'cms\\Controllers\\themeoptions' => 'modules\\cms\\controllers\\themeoptions.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'backend\\Controllers\\users' => 'modules\\backend\\controllers\\users.php',
  'system\\Controllers\\mailtemplates' => 'modules\\system\\controllers\\mailtemplates.php',
  'system\\Controllers\\mailbrandsettings' => 'modules\\system\\controllers\\mailbrandsettings.php',
  'backend\\Controllers\\accesslogs' => 'modules\\backend\\controllers\\accesslogs.php',
  'martin\\gitreposmanager\\Plugin' => 'plugins\\martin\\gitreposmanager\\Plugin.php',
  'martin\\gitreposmanager\\Controllers\\repos' => 'plugins\\martin\\gitreposmanager\\controllers\\repos.php',
  'Martin\\GitReposManager\\Models\\Repo' => 'plugins\\martin\\gitreposmanager\\models\\Repo.php',
);